url: https://y7kim.github.io
baseurl: parnassian-data-studio.github.io

# Site settings
title: Parnassian Data Studio
email: info@parnassian.xyz
description: "Website for Parnassian Data Studio / Parnassian Solutions, LLC. This is the data science contracting entity for Timothy Farkas."

# Team names, titles and social links
people:
  - name: Tim Farkas
    pic: 1
    position: Data Scientist
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/tim-farkas-5a7b93163/
      - title: github
        url: https://github.com/farkastime

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/parnassian-data-studio

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

